version: "3"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - hrs

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo_db
    networks:
      - hrs

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - hrs

networks:
  hrs:
    driver: bridge

volumes:
  mongo_db:
